package view;

import javax.swing.*;
import java.awt.*;

public class main extends javax.swing.JFrame {

    // Pannelli per le varie viste
    private CardLayout cardLayout;
    private JPanel cardPanel;
    private TerminaAbbonamento terminaAbbonamentoView;
    private AggiungiIscritto aggiungiIscrittoView; 
    private CercaIscritto cercaIscrittoView; 
    private MostraIscritti mostraIscrittiView; 
    private AbbonamentiAttivi abbonamentiView; 
    private StoricoAbbonamenti storicoAbbonamentiView; 
    private AggiungiAbbonamento aggiungiAbbonamentoView;

    public main() {
        initComponents();
        initCardLayout();
    }

    private void initCardLayout() {
        // Inizializza il CardLayout e il pannello che conterrà le varie view
        cardLayout = new CardLayout();
        cardPanel = new JPanel(cardLayout);

        // Inizializza i pannelli delle varie viste
        terminaAbbonamentoView = new TerminaAbbonamento();
        aggiungiIscrittoView = new AggiungiIscritto();
        cercaIscrittoView = new CercaIscritto();
        mostraIscrittiView = new MostraIscritti();
        abbonamentiView = new AbbonamentiAttivi();
        storicoAbbonamentiView = new StoricoAbbonamenti();
        aggiungiAbbonamentoView = new AggiungiAbbonamento();

        // Aggiungi i pannelli alla CardLayout
        cardPanel.add(terminaAbbonamentoView, "Termina Abbonamento");
        cardPanel.add(aggiungiIscrittoView, "Aggiungi Iscritto");
        cardPanel.add(cercaIscrittoView, "Cerca Iscritto");
        cardPanel.add(mostraIscrittiView, "Mostra Iscritti");
        cardPanel.add(abbonamentiView, "Mostra Abbonamenti Attivi");
        cardPanel.add(storicoAbbonamentiView, "Mostra Storico Abbonamenti");
        cardPanel.add(aggiungiAbbonamentoView, "Aggiungi Abbonamento");

        // Imposta la visibilità
        cardLayout.show(cardPanel, "Termina Abbonamento"); // Avvia con "Termina Abbonamento"
        getContentPane().add(cardPanel, BorderLayout.CENTER); // Il CardLayout al centro
    }

    // Metodo per passare alla vista Termina Abbonamento
    private void showTerminaAbbonamento() {
        cardLayout.show(cardPanel, "Termina Abbonamento");
    }

    // Metodo per passare alla vista Aggiungi Iscritto
    private void showAggiungiIscritto() {
        cardLayout.show(cardPanel, "Aggiungi Iscritto");
    }

    // Metodo per passare alla vista Cerca Iscritto
    private void showCercaIscritto() {
        cardLayout.show(cardPanel, "Cerca Iscritto");
    }

    // Metodo per passare alla vista Mostra Iscritti
    private void showMostraIscritti() {
        cardLayout.show(cardPanel, "Mostra Iscritti");
    }

    // Metodo per passare alla vista Mostra Abbonamenti Attivi
    private void showMostraAbbonamenti() {
        cardLayout.show(cardPanel, "Mostra Abbonamenti Attivi");
    }

    // Metodo per passare alla vista Mostra Storico Abbonamenti
    private void showMostraStoricoAbbonamenti() {
        cardLayout.show(cardPanel, "Mostra Storico Abbonamenti");
    }

    // Metodo per passare alla vista Aggiungi Abbonamento
    private void showAggiungiAbbonamento() {
        cardLayout.show(cardPanel, "Aggiungi Abbonamento");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {
        // I bottoni per cambiare la vista
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Aggiungi Iscritto");
        jButton1.addActionListener(evt -> showAggiungiIscritto());

        jButton2.setText("Cerca Iscritto");
        jButton2.addActionListener(evt -> showCercaIscritto());

        jButton3.setText("Mostra Iscritti");
        jButton3.addActionListener(evt -> showMostraIscritti());

        jButton4.setText("Mostra abbonamenti attivi");
        jButton4.addActionListener(evt -> showMostraAbbonamenti());

        jButton5.setText("Mostra storico abbonamenti");
        jButton5.addActionListener(evt -> showMostraStoricoAbbonamenti());

        jButton6.setText("Aggiungi Abbonamento");
        jButton6.addActionListener(evt -> showAggiungiAbbonamento());

        jButton7.setText("Termina Abbonamento");
        jButton7.addActionListener(evt -> showTerminaAbbonamento());

        // Layout
        JPanel buttonPanel = new JPanel();
        buttonPanel.setLayout(new BoxLayout(buttonPanel, BoxLayout.Y_AXIS)); // Usando BoxLayout per i pulsanti
        buttonPanel.add(jButton1);
        buttonPanel.add(jButton2);
        buttonPanel.add(jButton3);
        buttonPanel.add(jButton6);
        buttonPanel.add(jButton7);
        buttonPanel.add(jButton4);
        buttonPanel.add(jButton5);

        // Aggiungi il pannello dei pulsanti e il cardPanel al layout
        getContentPane().setLayout(new BorderLayout());
        getContentPane().add(buttonPanel, BorderLayout.WEST);  // I pulsanti sulla sinistra

        pack();
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variabili dichiarate
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    // Fine delle variabili dichiarate
}
